// TYPES FOR SEARCH REDUCER
export const GET_SEARCH = "GET_SEARCH";
export const GET_LOCATION = "GET_LOCATION";
export const SET_LOCATION = "SET_LOCATION";
export const SET_HOUSE_TYPE = "SET_HOUSE_TYPE";
export const SET_SEARCH_RADIUS = "SET_SEARCH_RADIUS";
export const SET_HOUSE_PRICE = "SET_HOUSE_PRICE";
export const SET_NUM_BEDROOMS = "SET_NUM_BEDROOMS";
export const GET_LISTINGS = "GET_LISTINGS";

// Listings reducer
export const SET_SELECTED_LISTING = "SET_SELECTED_LISTING";
export const GET_SELECTED_LISTING = "GET_SELECTED_LISTING";

// Area Reducer
export const GET_AREA_DATA = "GET_AREA_DATA";


