import { SET_SELECTED_LISTING, GET_LISTINGS } from "../actions/types";

const initialState = {
    selectedListing: null,
    fullscreen: false,
    listings: [
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "PropertyMutual",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/poppleton_close_coventry_2_bedroom_for_sale_112484771980941452.jpg",
            img_width: 400,
            keywords: "",
            latitude: 52.4089,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112484771980941452/title/5/1-1?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=112_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.52249,
            price: 140000,
            price_currency: "£",
            price_formatted: "£140,000",
            price_high: 140000,
            price_low: 140000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "If you are looking for a buy to let property that you can rent stra...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/poppleton_close_coventry_2_bedroom_for_sale_112484771980941452.jpg",
            thumb_width: 80,
            title: "Poppleton Close",
            updated_in_days: 84,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_flat_for_sale_queens_road_coventry_112837350563099086.jpg",
            img_width: 400,
            keywords: "Leasehold, Shared Equity",
            latitude: 52.404247,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112837350563099086/title/5/1-2?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.517846,
            price: 185000,
            price_currency: "£",
            price_formatted: "£185,000",
            price_high: 185000,
            price_low: 185000,
            price_type: "185000",
            property_type: "flat",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "Help to buy available help to buy price 148,000 contemporary design...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_flat_for_sale_queens_road_coventry_112837350563099086.jpg",
            thumb_width: 80,
            title: "Flat for sale, Queens Road",
            updated_in_days: 13,
            updated_in_days_formatted: "first seen last week"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Home.co.uk",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/terraced_house_112868457366597282.jpg",
            img_width: 400,
            keywords: "Garden, Terraced, Reception, Gas Central Heating",
            latitude: 52.419429,
            lister_name: "Whitegates",
            lister_url:
                "https://www.nestoria.co.uk/detail/0000000112868457366597282/title/5/1-3?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 10,
            longitude: -1.511247,
            price: 124500,
            price_currency: "£",
            price_formatted: "£124,500",
            price_high: 124500,
            price_low: 124500,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Two bedroom, mid-terraced property situated close to the city centr...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/terraced_house_112868457366597282.jpg",
            thumb_width: 80,
            title: "Somerset Road, Radford, Coventry, West Midlands, CV1",
            updated_in_days: 22,
            updated_in_days_formatted: "first seen 3 weeks ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 6,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Mouseprice",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/gloucester_street_spon_end_coventry_w_112763888658780383.jpg",
            img_width: 400,
            keywords: "Kitchen",
            latitude: 52.409706,
            lister_url:
                "https://www.nestoria.co.uk/detail/0000000112763888658780383/title/5/1-4?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=370855_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.5206975,
            price: 249995,
            price_currency: "£",
            price_formatted: "£249,995",
            price_high: 249995,
            price_low: 249995,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Great investment. Six lettable rooms. Rent being achieved of circa ...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/gloucester_street_spon_end_coventry_w_112763888658780383.jpg",
            thumb_width: 80,
            title: "House for sale, COVENTRY",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "OneDome",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bedrooms_property_for_sale_112738523152030560.jpg",
            img_width: 400,
            keywords: "Garden, Double Bedroom, Kitchen, Loft",
            latitude: 52.40507,
            lister_url:
                "https://www.nestoria.co.uk/detail/0000000112738523152030560/title/5/1-5?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.495436,
            price: 184950,
            price_currency: "£",
            price_formatted: "£184,950",
            price_high: 184950,
            price_low: 184950,
            price_type: "fixed",
            property_type: "flat",
            room_number: 3,
            size: 0,
            size_type: "net",
            summary:
                "Full description attention investors great investment opportunity t...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bedrooms_property_for_sale_112738523152030560.jpg",
            thumb_width: 80,
            title: "Charterhouse Road - Double Bedroom",
            updated_in_days: 43,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "NetHousePrices",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bedroom_terraced_house_112720584987273578.jpg",
            img_width: 400,
            keywords: "Garden, Terraced, Double Bedroom, Kitchen",
            latitude: 52.405067,
            lister_name: "Envisage",
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112720584987273578/title/5/1-6?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.4954356,
            price: 184950,
            price_currency: "£",
            price_formatted: "£184,950",
            price_high: 184950,
            price_low: 184950,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Full description attention investors great investment opportunity t...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bedroom_terraced_house_112720584987273578.jpg",
            thumb_width: 80,
            title: "Charterhouse Road, Coventry, CV1",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 1,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/1_bed_flat_for_sale_earlsdon_park_village_coventry_112763838528027359.jpg",
            img_width: 400,
            keywords: "Leasehold, Garden, Refurbished, Lift, Reception",
            latitude: 52.404613,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763838528027359/title/5/1-7?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.523766,
            price: 202950,
            price_currency: "£",
            price_formatted: "£202,950",
            price_high: 202950,
            price_low: 202950,
            price_type: "202950",
            property_type: "flat",
            room_number: 1,
            size: 0,
            size_type: "net",
            summary:
                "The village will be home to over 350 local older residents, with 26...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/1_bed_flat_for_sale_earlsdon_park_village_coventry_112763838528027359.jpg",
            thumb_width: 80,
            title: "Earlsdon Park Village - Refurbished",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bed_flat_for_sale_electric_wharf_coventry_112923943396125217.jpg",
            img_width: 400,
            keywords: "No Chain, Kitchen, Dishwasher, Modern, Parking",
            latitude: 52.41809,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112923943396125217/title/5/1-8?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.511387,
            price: 190000,
            price_currency: "£",
            price_formatted: "£190,000",
            price_high: 190000,
            price_low: 190000,
            price_type: "190000",
            property_type: "flat",
            room_number: 3,
            size: 0,
            size_type: "net",
            summary:
                "No upward chain this and first floor apartment is situated in a sou...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bed_flat_for_sale_electric_wharf_coventry_112923943396125217.jpg",
            thumb_width: 80,
            title: "Flat for sale, Electric Wharf",
            updated_in_days: 13,
            updated_in_days_formatted: "first seen last week"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "PropertyMutual",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/quarryfield_lane_coventry_3_bedroom_for_sale_112985936995848171.jpg",
            img_width: 400,
            keywords: "Terraced, Double Bedroom, Modern",
            latitude: 52.4011,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112985936995848171/title/5/1-9?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=112_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.5019,
            price: 245000,
            price_currency: "£",
            price_formatted: "£245,000",
            price_high: 245000,
            price_low: 245000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "This three double bedroom end of terrace house in the modern parksi...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/quarryfield_lane_coventry_3_bedroom_for_sale_112985936995848171.jpg",
            thumb_width: 80,
            title: "Quarryfield Lane - Terraced, Modern",
            updated_in_days: 3,
            updated_in_days_formatted: "first seen 3 days ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_flat_for_sale_meridian_point_coventry_112763875560421669.jpg",
            img_width: 400,
            keywords: "En suite, Balcony, Double Bedroom, Kitchen, Parking",
            latitude: 52.404243,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763875560421669/title/5/1-10?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.510364,
            price: 185000,
            price_currency: "£",
            price_formatted: "£185,000",
            price_high: 185000,
            price_low: 185000,
            price_type: "185000",
            property_type: "flat",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "The accommodation affords: entrance hallway, large living kitchen, ...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_flat_for_sale_meridian_point_coventry_112763875560421669.jpg",
            thumb_width: 80,
            title: "Flat for sale, Meridian Point",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bed_terraced_for_sale_john_grace_street_coventry_112763858802974461.jpg",
            img_width: 400,
            keywords: "Garden, No Chain, Terraced, Garage, Kitchen, Listed",
            latitude: 52.39752,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763858802974461/title/5/1-11?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.502076,
            price: 225000,
            price_currency: "£",
            price_formatted: "£225,000",
            price_high: 225000,
            price_low: 225000,
            price_type: "225000",
            property_type: "house",
            room_number: 3,
            size: 0,
            size_type: "net",
            summary:
                "Reeds rains coventry are pleased to offer with no upward chain this...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bed_terraced_for_sale_john_grace_street_coventry_112763858802974461.jpg",
            thumb_width: 80,
            title: "John Grace Street - Garden, No Chain",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_flat_for_sale_rathborne_court_coventry_112763840509186147.jpg",
            img_width: 400,
            keywords:
                "Leasehold, En suite, Double Bedroom, Kitchen, Modern, Parking",
            latitude: 52.42353,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763840509186147/title/5/1-12?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.494681,
            price: 114995,
            price_currency: "£",
            price_formatted: "£114,995",
            price_high: 114995,
            price_low: 114995,
            price_type: "114995",
            property_type: "flat",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "Attention investors earn immediate return on investment built in 20...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_flat_for_sale_rathborne_court_coventry_112763840509186147.jpg",
            thumb_width: 80,
            title: "Rathborne Court - Leasehold, En Suite",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "PropertyMutual",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/friars_road_coventry_2_bedroom_for_sale_112484769317195689.jpg",
            img_width: 400,
            keywords: "Double Bedroom",
            latitude: 52.4045,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112484769317195689/title/5/1-13?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=112_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.51017,
            price: 180000,
            price_currency: "£",
            price_formatted: "£180,000",
            price_high: 180000,
            price_low: 180000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Are you an investor looking for a town centre apartment? Then look ...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/friars_road_coventry_2_bedroom_for_sale_112484769317195689.jpg",
            thumb_width: 80,
            title: "House for sale, Friars Road",
            updated_in_days: 3,
            updated_in_days_formatted: "first seen 3 days ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bed_terraced_for_sale_st_christians_road_coventry_112763853452313295.jpg",
            img_width: 400,
            keywords: "Garden, No Chain, Terraced, Kitchen, Modern, Parking",
            latitude: 52.396805,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763853452313295/title/5/1-14?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.500806,
            price: 210000,
            price_currency: "£",
            price_formatted: "£210,000",
            price_high: 210000,
            price_low: 210000,
            price_type: "210000",
            property_type: "house",
            room_number: 3,
            size: 0,
            size_type: "net",
            summary:
                "Guide price 210,000 220,000 three-bedroom mid-terraced home that ha...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bed_terraced_for_sale_st_christians_road_coventry_112763853452313295.jpg",
            thumb_width: 80,
            title: "St. Christians Road - Garden, Modern",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bed_terraced_for_sale_honeyfield_road_coventry_112763795088025093.jpg",
            img_width: 400,
            keywords: "No Chain, Terraced, Kitchen, Reception",
            latitude: 52.42104,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763795088025093/title/5/1-15?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.504635,
            price: 130000,
            price_currency: "£",
            price_formatted: "£130,000",
            price_high: 130000,
            price_low: 130000,
            price_type: "130000",
            property_type: "house",
            room_number: 3,
            size: 0,
            size_type: "net",
            summary:
                "Offered for sale with no onward chain is this three bedroom terrace...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bed_terraced_for_sale_honeyfield_road_coventry_112763795088025093.jpg",
            thumb_width: 80,
            title: "Honeyfield Road - Terraced, No Chain",
            updated_in_days: 21,
            updated_in_days_formatted: "first seen 3 weeks ago"
        },
        {
            bathroom_number: 3,
            bedroom_number: 5,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/5_bed_semi_detached_for_sale_chiltern_leys_coventry_112967290677902540.jpg",
            img_width: 400,
            keywords:
                "Garden, Semi-Detached, Fireplace, Double Bedroom, Garage, Kitchen, Dishwasher",
            latitude: 52.41688,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112967290677902540/title/5/1-16?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.528089,
            price: 245000,
            price_currency: "£",
            price_formatted: "£245,000",
            price_high: 245000,
            price_low: 245000,
            price_type: "245000",
            property_type: "house",
            room_number: 5,
            size: 0,
            size_type: "net",
            summary:
                "Traditional 1930's family home set in the heart of coundon position...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/5_bed_semi_detached_for_sale_chiltern_leys_coventry_112967290677902540.jpg",
            thumb_width: 80,
            title: "House for sale, Chiltern Leys",
            updated_in_days: 6,
            updated_in_days_formatted: "first seen 6 days ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 4,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Home.co.uk",
            img_height: 300,
            img_url:
                "https://resources.nestimg.com/nestoria/img/noimage/desktop/house/5.png",
            img_width: 400,
            keywords: "Detached, Parking",
            latitude: 52.394026,
            lister_name: "Lovetts",
            lister_url:
                "https://www.nestoria.co.uk/detail/0000000112973517390343173/title/5/1-17?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 10,
            longitude: -1.514304,
            price: 250000,
            price_currency: "£",
            price_formatted: "£250,000",
            price_high: 250000,
            price_low: 250000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Unique opportunity, 4 bedroom detached property in need of improvem...",
            thumb_height: 60,
            thumb_url:
                "https://resources.nestimg.com/nestoria/img/noimage/mobile/house/1.png",
            thumb_width: 80,
            title: "Townsend Croft, Styvechale, Coventry, CV3",
            updated_in_days: 5,
            updated_in_days_formatted: "first seen 5 days ago"
        },
        {
            bathroom_number: 2,
            bedroom_number: 6,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/6_bed_terraced_for_sale_gloucester_street_coventry_112763859401985092.jpg",
            img_width: 400,
            keywords: "No Chain, Terraced, Victorian, Kitchen, Listed",
            latitude: 52.409706,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763859401985092/title/5/1-18?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.520698,
            price: 250000,
            price_currency: "£",
            price_formatted: "£250,000",
            price_high: 250000,
            price_low: 250000,
            price_type: "250000",
            property_type: "house",
            room_number: 6,
            size: 0,
            size_type: "net",
            summary:
                "Reeds rains coventry are pleased to offer with no upward chain this...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/6_bed_terraced_for_sale_gloucester_street_coventry_112763859401985092.jpg",
            thumb_width: 80,
            title: "Gloucester Street - Listed, Terraced",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: 1,
            bedroom_number: 1,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/1_bed_flat_for_sale_greyfriars_road_coventry_112763793747575527.jpg",
            img_width: 400,
            keywords: "Leasehold, Furnished, Kitchen, Modern, Parking",
            latitude: 52.405636,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763793747575527/title/5/1-19?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.514524,
            price: 135000,
            price_currency: "£",
            price_formatted: "£135,000",
            price_high: 135000,
            price_low: 135000,
            price_type: "135000",
            property_type: "flat",
            room_number: 1,
            size: 0,
            size_type: "net",
            summary:
                "Descriptiona modern one bedroom fully furnished city centre apartme...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/1_bed_flat_for_sale_greyfriars_road_coventry_112763793747575527.jpg",
            thumb_width: 80,
            title: "Greyfriars Road - Furnished, Modern",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_flat_for_sale_beauchamp_house_coventry_112763795637426665.jpg",
            img_width: 400,
            keywords: "En suite, Kitchen",
            latitude: 52.405636,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763795637426665/title/5/1-20?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.514524,
            price: 165000,
            price_currency: "£",
            price_formatted: "£165,000",
            price_high: 165000,
            price_low: 165000,
            price_type: "165000",
            property_type: "flat",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "Two bedroom city centre located apartment in beauchamp house. The p...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_flat_for_sale_beauchamp_house_coventry_112763795637426665.jpg",
            thumb_width: 80,
            title: "Beauchamp House - En Suite",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/3_bed_terraced_for_sale_irving_road_coventry_112763799843893661.jpg",
            img_width: 400,
            keywords:
                "Garden, Needs Modernisation, No Chain, Terraced, Kitchen, Reception",
            latitude: 52.40345,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763799843893661/title/5/1-21?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.494998,
            price: 189950,
            price_currency: "£",
            price_formatted: "£189,950",
            price_high: 189950,
            price_low: 189950,
            price_type: "189950",
            property_type: "house",
            room_number: 3,
            size: 0,
            size_type: "net",
            summary:
                "The property is ideally situated for investment and is available wi...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/3_bed_terraced_for_sale_irving_road_coventry_112763799843893661.jpg",
            thumb_width: 80,
            title: "House for sale, Irving Road - Garden",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: 2,
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_terraced_for_sale_smith_street_coventry_112763794622820163.jpg",
            img_width: 400,
            keywords:
                "Garden, No Chain, Terraced, Double Bedroom, Kitchen, Gas Central Heating",
            latitude: 52.418793,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763794622820163/title/5/1-22?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.493823,
            price: 115000,
            price_currency: "£",
            price_formatted: "£115,000",
            price_high: 115000,
            price_low: 115000,
            price_type: "115000",
            property_type: "house",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "Ideal first time buy or investment property, the accommodation feat...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_terraced_for_sale_smith_street_coventry_112763794622820163.jpg",
            thumb_width: 80,
            title: "House for sale, Smith Street - Garden",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Home.co.uk",
            img_height: 300,
            img_url:
                "https://resources.nestimg.com/nestoria/img/noimage/desktop/house/4.png",
            img_width: 400,
            keywords: "Semi-Detached, Terraced, Kitchen, Off Street Parking",
            latitude: 52.398199,
            lister_name: "Elizabeth Davenport",
            lister_url:
                "https://www.nestoria.co.uk/detail/0000000112385746946807614/title/5/1-23?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 10,
            longitude: -1.50372,
            price: 220000,
            price_currency: "£",
            price_formatted: "£220,000",
            price_high: 220000,
            price_low: 220000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Three bedrooms ~ off street parking ~ modern kitchen & bathroom ~ o...",
            thumb_height: 60,
            thumb_url:
                "https://resources.nestimg.com/nestoria/img/noimage/mobile/house/3.png",
            thumb_width: 80,
            title: "Mile Lane, Cheylesmore, Coventry",
            updated_in_days: 100,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 3,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Home.co.uk",
            img_height: 300,
            img_url:
                "https://resources.nestimg.com/nestoria/img/noimage/desktop/house/4.png",
            img_width: 400,
            keywords:
                "Garden, Semi-Detached, Garage, Kitchen, Gas Central Heating",
            latitude: 52.4012,
            lister_name: "Complete",
            lister_url:
                "https://www.nestoria.co.uk/detail/0000000112664019646644789/title/5/1-24?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 10,
            longitude: -1.492561,
            price: 190000,
            price_currency: "£",
            price_formatted: "£190,000",
            price_high: 190000,
            price_low: 190000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "An opportunity to buy a semi detached property in the sought after ...",
            thumb_height: 60,
            thumb_url:
                "https://resources.nestimg.com/nestoria/img/noimage/mobile/house/5.png",
            thumb_width: 80,
            title: "Terry Road, Stoke, Coventry - Garden",
            updated_in_days: 54,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "PropertyMutual",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/boiler_house_coventry_2_bedroom_for_sale_112484771162893475.jpg",
            img_width: 400,
            keywords: "",
            latitude: 52.4181,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112484771162893475/title/5/1-25?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=112_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.5114,
            price: 220000,
            price_currency: "£",
            price_formatted: "£220,000",
            price_high: 220000,
            price_low: 220000,
            price_type: "fixed",
            property_type: "house",
            size: 0,
            size_type: "net",
            summary:
                "Investors only penthouse style apartment located in a secure gated ...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/boiler_house_coventry_2_bedroom_for_sale_112484771162893475.jpg",
            thumb_width: 80,
            title: "House for sale, Boiler House",
            updated_in_days: 84,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_flat_for_sale_david_road_coventry_112763817176849489.jpg",
            img_width: 400,
            keywords: "Double Bedroom, Kitchen, Parking",
            latitude: 52.404827,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763817176849489/title/5/1-26?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.49338,
            price: 114000,
            price_currency: "£",
            price_formatted: "£114,000",
            price_high: 114000,
            price_low: 114000,
            price_type: "114000",
            property_type: "flat",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "A two bedroom apartment offered for sale in the stoke area of coven...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_flat_for_sale_david_road_coventry_112763817176849489.jpg",
            thumb_width: 80,
            title: "Flat for sale, David Road",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        },
        {
            bathroom_number: "",
            bedroom_number: 2,
            car_spaces: "",
            commission: 0,
            construction_year: 0,
            datasource_name: "Property Pigeon",
            img_height: 300,
            img_url:
                "https://imgs.nestimg.com/2_bed_flat_for_sale_blakeley_court_coventry_112763812483193824.jpg",
            img_width: 400,
            keywords:
                "Shared Garden, No Chain, Double Bedroom, Kitchen, Modern, Parking, Gas Central Heating",
            latitude: 52.425896,
            lister_url:
                "https://www.nestoria.co.uk/detail-int/0000000112763812483193824/title/5/1-27?serpUid=&pt=1&ot=1&l=electric-wharf-cv1&did=95_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
            listing_type: "buy",
            location_accuracy: 9,
            longitude: -1.511492,
            price: 120000,
            price_currency: "£",
            price_formatted: "£120,000",
            price_high: 120000,
            price_low: 120000,
            price_type: "120000",
            property_type: "flat",
            room_number: 2,
            size: 0,
            size_type: "net",
            summary:
                "Book your viewing on line on our website currently let out at 650 p...",
            thumb_height: 60,
            thumb_url:
                "https://imgs.nestimg.com/medium/2_bed_flat_for_sale_blakeley_court_coventry_112763812483193824.jpg",
            thumb_width: 80,
            title: "Flat for sale, Blakeley Court",
            updated_in_days: 39,
            updated_in_days_formatted: "first seen over a month ago"
        }
    ]
};

export default (state = initialState, action) => {
    switch (action.type) {
        case GET_LISTINGS:
            return {
                ...state,
                result: action.payload,
                listings: action.payload.response.listings
            };
        case SET_SELECTED_LISTING:
            return {
                ...state,
                fullscreen: action.payload === state.selectedListing,
                selectedListing: action.payload
            };
        // case GET_SELECTED_LISTING:
        //     break;
        default:
            return state;
    }
};
